#!/bin/bash

python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput

DOCKER_HOST_IP=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')

if [[ -z $1 ]]
then
  gunicorn -c /app/docker/app/gunicorn-config.py keithvaluation.wsgi
else
  exec $@
fi
