---
- template: src=dc-prod.j2 dest=/etc/docker-compose.kv.yml mode=0644

- name: Write envvar file
  template:
    src: envvars.j2
    dest: /etc/kv-docker.env
    mode: 0600
    owner: root

- name: Build all docker images
  command: dc build

- name: Stop existing containers
  command: dc stop -t 10 app db

- name: Remove existing containers
  command: dc rm -fv app db

- name: Start containers
  command: dc up -d app db

- include: data.yml

- command: docker images --filter dangling=true -q
  register: dangling_images

- name: Remove dangling images
  shell: "docker rmi {{ dangling_images.stdout_lines | join(' ') }}"
  when: dangling_images.stdout
  ignore_errors: true
