---
- template: src=docker-compose.prod.yml.j2 dest=/etc/docker-compose.kv.yml mode=0600
- template: src=dc.j2 dest=/usr/local/bin/dc-kv mode=0755

- name: Build all docker images
  command: dc-kv build

- name: Stop existing containers
  command: dc-kv stop -t 10

- include: ssl.yml domain={{ admin_hostname }}

- name: Remove existing containers
  command: dc-kv rm -f

- name: Start containers
  command: dc-kv up -d

#- include: data.yml

- command: docker images --filter dangling=true -q
  register: dangling_images

- name: Remove dangling images
  shell: "docker rmi {{ dangling_images.stdout_lines | join(' ') }}"
  when: dangling_images.stdout
  ignore_errors: true
