---
- template: src=docker-compose.prod.yml.j2 dest=/etc/docker-compose.kv.yml mode=0600
- template: src=dc.j2 dest=/usr/local/bin/dc-kv mode=0755

- name: Build all docker images
  command: dc-kv build

- name: Start containers (except https)
  command: dc-kv up -d nginx_http

- include_tasks: data.yml

- include_tasks: ssl.yml
  vars:
    domain: "{{ admin_hostname }}"
    volume: "{{ project_name }}_letsencrypt"
    refresh_command: "/usr/local/bin/dc-kv kill -s HUP nginx_https"
  tags:
    - ssl

- include_tasks: ssl.yml
  vars:
    domain: "www.{{ app_hostname }}"
    volume: "{{ project_name }}_letsencrypt"
    refresh_command: "/usr/local/bin/dc-kv kill -s HUP nginx_https"
  tags:
    - ssl

- name: Start https containers
  command: dc-kv up -d nginx_https

- command: docker images --filter dangling=true -q
  register: dangling_images

- name: Remove dangling images
  shell: "docker rmi {{ dangling_images.stdout_lines | join(' ') }}"
  when: dangling_images.stdout
  ignore_errors: true
