---
- name: Install base packages
  apt: name={{item}} state=present
  with_items:
    - git
    - aptitude
- name: Upgrade all packages
  apt: upgrade=safe
- include: repo.yml
- include: containers.yml
  
  
