---
- name: Install base packages
  apt: name={{item}} state=present update_cache=true
  with_items:
    - git
    - docker-compose
    - python3-pip

- name: Upgrade all packages
  apt: upgrade=safe

- name: Create docker-run dir
  file: state=directory name=/docker-run mode=0755

- include_tasks: repo.yml
- include_tasks: containers.yml
- include_tasks: backup.yml

