---
- name: Create docker-run dir
  file: state=directory name=/docker-run mode=0755

- name: Upload config file for {{ domain }}
  template: src=le-config.ini.j2 dest=/docker-run/letsencrypt-{{ domain }}.ini

- name: Run letsencrypt for {{ domain }}
  command: >
    docker run
    --rm
    -v "letsencrypt:/etc/letsencrypt"
    -v "/docker-run/letsencrypt-{{ domain }}.ini:/etc/letsencrypt/cli.ini"
    -p 443:443
    quay.io/letsencrypt/letsencrypt:latest
    certonly -c /etc/letsencrypt/cli.ini
