app:
  command: "tail -f /dev/null"
  volumes:
   - ".:/app"
  environment:
    DJANGO_DEBUG: 'y'
    SITE_HOSTNAME: 'kv.dev'
    DJANGO_STATIC_HOSTNAME: 'www.kv.dev:28080'
    DJANGO_STATIC_PATH: '/static/'
admin:
  command: "tail -f /dev/null"
  environment:
    SITE_HOSTNAME: 'kv-admin.dev'
    DJANGO_STATIC_HOSTNAME: 'www.kv.dev:28443'
    DJANGO_STATIC_PATH: '/static/'
nginx:
  ports:
   - "28080:80"
   - "28443:443"
  environment:
    ADMIN_SSL_CERT: |
      -----BEGIN CERTIFICATE-----
      MIIDUjCCAjqgAwIBAgIJAPUN19FpexYaMA0GCSqGSIb3DQEBBQUAMFExCzAJBgNV
      BAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTESMBAGA1UEBxMJQ2hhcmxv
      dHRlMRUwEwYDVQQDEwxrdi1hZG1pbi5kZXYwHhcNMTUxMDAzMTk1NzM3WhcNMjUx
      MDAzMTk1NzM3WjBRMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xp
      bmExEjAQBgNVBAcTCUNoYXJsb3R0ZTEVMBMGA1UEAxMMa3YtYWRtaW4uZGV2MIIB
      IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA01LOIvpB+/No5w1aVIcjLa90
      YT/L6MRGakhjIpFftGuz36//tsRwX5EOcybDJtGSdFCh1wm280ETTEmRX9mIfl9G
      6iACtvf0MQGImwf8NJmw0lAJpnM3nH32RBVHGgWzlJ5T/3nX3YyoVgXV3F4JHJhi
      Vpb0BSBd8kBklAumD071vsEHI6s3mgzUGTCF8zb7kEch7MJoIUHC7rYme6KGUaY4
      Wok/m8/YsLLIB3Nb4NLczS8DDClkpkB9qQWsiBIasCjpmhzDVrVNuTjnPBayXhtw
      qTyhJI3XdkcqQV6mjreI6nAjOF9axRXTL+OOv8/Ems2NfRMv8uswBr+07VzvGQID
      AQABoy0wKzAJBgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQEAwIE8DALBgNVHQ8EBAMC
      BSAwDQYJKoZIhvcNAQEFBQADggEBAEB2LjYkO7V3duDQwZxix1bP+gTNvyeJ7GGq
      XTzShdBQuqXwTKEm0lgixTUGa6ad43CF2AlTaSkm42lmfhImSk53qFdpwrdh++Kl
      CQFMaM/7YSUjbx9c3/jco84cHcQAHwbmyT4CufFJ3Jb6KhkD/+F0kxdVyyuUmbbC
      TUx9mGIUVO6gCkxHSTOE4ODYgSeZiMCdbDGxW2cgNuWy/tIsoNI+Q5dNWKD7Pny9
      QjWlRSQZZLwemSPV1lnKjm6l1l4KyuDUPmtkuJuH7mjf0oDyunAPd/m+UAmM3jP8
      9ISyzus4rwQsYTJuJQSpB9n3S0oD5+b4ymzo97Tdq9uR+4aK9HY=
      -----END CERTIFICATE-----
    ADMIN_SSL_KEY: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA01LOIvpB+/No5w1aVIcjLa90YT/L6MRGakhjIpFftGuz36//
      tsRwX5EOcybDJtGSdFCh1wm280ETTEmRX9mIfl9G6iACtvf0MQGImwf8NJmw0lAJ
      pnM3nH32RBVHGgWzlJ5T/3nX3YyoVgXV3F4JHJhiVpb0BSBd8kBklAumD071vsEH
      I6s3mgzUGTCF8zb7kEch7MJoIUHC7rYme6KGUaY4Wok/m8/YsLLIB3Nb4NLczS8D
      DClkpkB9qQWsiBIasCjpmhzDVrVNuTjnPBayXhtwqTyhJI3XdkcqQV6mjreI6nAj
      OF9axRXTL+OOv8/Ems2NfRMv8uswBr+07VzvGQIDAQABAoIBAFu5T1wDP+y6JEhV
      lWWnGm/T/jHP3RP1TZMIRG9WpjHLpdFrtRSBgz0X2yvEIWSSBn2SGg0aXFyNXHD6
      Za0y4HnppQAuUL9WNJmozsBr4N577zH6J5Yl4Hd+fQvkKG51FxNk/ZSgMEArs01T
      TxZNgqr0wYpQDy7Cc8SYio9v1u5BTtr18MgwmVcSPTHsQmLchW0CEsoKhUiMi0G0
      4QTdhNaY5sIGJj2xhi2UXmRTEToRcemCCGc6jZVJX8/ZtRSTbH6nHJdT0WaksVaG
      f0LYJ8k79ozryEAU+Y97RNSUQPmITBeub0NzcwCezDvrVW0GaWKuekeK0ktKAjm2
      TteTOBkCgYEA/f64a1EIpQ6bss25SO/QCg7leZra26t9SaUn54x/yril0/wj8jOH
      QjHHKPun9Jpcp4L0mBVebPzreR0eRRNGDceKYOqOVdyNxIDdfeZ6J3tUf6aa3c2j
      YpY8eGBTFcTAmUkZk2fxQrku7AiwyPwBpkoYnE2GHWXU3i3BRynaIMcCgYEA1P3a
      Y7f77H0eVQpeRVrQr1z98dzmKzg/lrtBE9jGq6ZE5vF5upc+vlqKGlVFeg5Vs74S
      AsY9qvgWUTqyWkdF5OVrQvQhAUyGrdG1ze/VEl6z3UscZdX6VbuWGCs6NH3s4MNj
      NOJZxNq6/uMqexoKNqPdDaRa0hh8oWfiHH/MUR8CgYAmpMGEOmD5U96mdpxRF4Ns
      dFW/iarwrwex07ndhcfPnQZF2V/SsrpKfO5TMu6bzXx5U/hIxz+Fj3l4BNEdK1CG
      Oiy4kBc1wweitQR96jn9lcsGXN/FDUtlbXwnyGf7sOKor7F/dtoDD8+uw6e5/HV3
      ymAyL61O/bZEU2vLmvd/8wKBgQC3JBBE7k6QaoVKWj/1IsGOCEfTUD4Zq6QB18F9
      b0hlD/LvIXOqHaK1yuQ1AF1dNjY695RFDnC4Mdn+vpndRquyxhIU4BYBJ+wmScwp
      568uvH+sKImihvtZ/JJy9bh2qlCkc106e+b0fZ+My4gbkah2ky/gKxJs1OFVaB3k
      o37rwQKBgQC+hs4TJz7+pBQgEvXqJIAOc6dCDaCgHmdQ38Rzp2TuYCNzPCqCUWop
      MlNm9DZjHV2M06vvA+b+xj1yElf0UGzJfFaSJZNEUMbXZ6tCUbBQ86wvqg8wUfQP
      iuFWXLS3GZqTYvy5ioO/f57qEXus93HIg9AaraTHi6dXBPDJ6AsY2g==
      -----END RSA PRIVATE KEY-----

