version: '2.1'
services:
  app: &app
    command: "tail -f /dev/null"
    volumes:
     - ".:/app"
    environment: &env
      DJANGO_DEBUG: 'y'
      SITE_HOSTNAME: &app_host "${SITE_HOSTNAME:-dev.keithvaluation.com}"
      DJANGO_STATIC_ROOT: "${DJANGO_STATIC_HOSTNAME:-www.dev.keithvaluation.com}/content"
  admin:
    <<: *app
    environment:
      <<: *env
      SITE_HOSTNAME: &admin_host "${ADMIN_SITE_HOSTNAME:-dev-admin.keithvaluation.com}"
      DJANGO_STATIC_ROOT: "${ADMIN_DJANGO_STATIC_HOSTNAME:-dev-admin.keithvaluation.com}/content"
      DJANGO_ADMIN: 'y'

  nginx_http:
    ports:
      - "0.0.0.0:80:80"
    environment: &nginx_env
      APP_HOSTNAME: *app_host
      ADMIN_HOSTNAME: *admin_host

  nginx_https:
    environment:
      <<: *nginx_env
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - "./dev-ssl:/etc/letsencrypt/live/${ADMIN_SITE_HOSTNAME}"
      - "./dev-ssl:/etc/letsencrypt/live/www.${SITE_HOSTNAME}"
