app:
  build: .
  dockerfile: docker/app/Dockerfile
  volumes:
    - "kv_database:/data"
    - "kv_media:/media"
  links:
    - memcached
admin:
  build: .
  dockerfile: docker/app/Dockerfile
  volumes_from:
    - app
  links:
    - memcached
  environment:
    DJANGO_ADMIN: 'y'
memcached:
  image: memcached:1.4.24
  command: memcached -m 128
nginx:
  build: docker/nginx
  links:
    - app
    - admin
  volumes_from:
    - app
