version: '2'
services:
  app: &app
    command: "tail -f /dev/null"
    volumes:
     - ".:/app"
    environment: &env
      DJANGO_DEBUG: 'y'
      SITE_HOSTNAME: &app_host 'dev.keithvaluation.com'
      DJANGO_STATIC_HOSTNAME: 'www.dev.keithvaluation.com'
      DJANGO_STATIC_PATH: '/static/'
  admin:
    <<: *app
    environment:
      <<: *env
      SITE_HOSTNAME: &admin_host 'dev-admin.keithvaluation.com'
      DJANGO_STATIC_HOSTNAME: 'dev-admin.keithvaluation.com'

  nginx_http:
    ports:
      - "127.0.7.1:80:80"
    environment: &nginx_env
      APP_HOSTNAME: *app_host
      ADMIN_HOSTNAME: *admin_host

  nginx_https:
    environment:
      <<: *nginx_env
    ports:
      - "127.0.7.1:443:443"
    volumes:
      - "./dev-ssl:/etc/letsencrypt/live/dev-admin.keithvaluation.com"
      - "./dev-ssl:/etc/letsencrypt/live/www.dev.keithvaluation.com"
