version: '2'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - "database:/data"
      - "media:/media"
    depends_on:
      - memcached
    environment:
      GOOGLE_MAPS_API_KEY: "AIzaSyAWMUQem-esNXNeN-wmY1DdgETAep4vvJ4"

  admin:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes_from:
      - app
    depends_on:
      - memcached
    environment:
      DJANGO_ADMIN: 'y'

  memcached:
    image: memcached:1.6
    command: memcached -m 128

  nginx_http: &nginx
    build:
      context: &nginx_context docker/nginx
      args:
        PROTOCOL: http
    depends_on:
      - app
      - admin
    volumes_from:
      - app

  nginx_https:
    <<: *nginx
    build:
      context: *nginx_context
      args:
        PROTOCOL: https

volumes:
  database: {}
  media: {}
