app: &app
  build: .
  ports:
   - "18000:8000"
  expose:
    - "8000"
  volumes:
   - ".:/app"
  volumes_from:
   - dbdata
  environment:
    DJANGO_EXTENSIONS: 'y'
dbdata:
  build: .
  volumes:
   - /data
nginx:
  build: docker/nginx
  environment:
    SERVER_HOSTNAME: 'kv.dev'
    ADMIN_HOSTNAME: 'kv-admin.dev'
  links:
    - app
  volumes_from:
    - dbdata
  ports:
   - "28080:80"
   - "28443:443"
