app:
  command: "tail -f /dev/null"
  volumes:
   - ".:/app"
  environment:
    DJANGO_DEBUG: 'y'
    SITE_HOSTNAME: 'kv.dev'
    DJANGO_STATIC_HOSTNAME: 'www.kv.dev:28080'
    DJANGO_STATIC_PATH: '/static/'
admin:
  command: "tail -f /dev/null"
  environment:
    SITE_HOSTNAME: 'kv-admin.dev'
    DJANGO_STATIC_HOSTNAME: 'www.kv.dev:28443'
    DJANGO_STATIC_PATH: '/static/'
nginx:
  ports:
   - "28080:80"
   - "28443:443"
  volumes:
    - "./dev-ssl:/etc/letsencrypt/live/kv-admin.dev"

