app: &app
  build: .
  dockerfile: docker/app/Dockerfile
admin:
  <<: *app
  environment:
    DJANGO_ADMIN: 'y'
memcached:
  image: memcached:1.4.24
  command: memcached -m 128
nginx:
  build: docker/nginx
