# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-26 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import keithvaluation.models.property


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0007_auto_20171125_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=keithvaluation.models.property.image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='huntinglease',
            name='property',
        ),
        migrations.DeleteModel(
            name='LeasedProperty',
        ),
        migrations.RemoveField(
            model_name='property',
            name='aerial_photo',
        ),
        migrations.AddField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='available_for_lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='available_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='available_to_hunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[(b'NC', b'NC')], max_length=256),
        ),
        migrations.DeleteModel(
            name='HuntingLease',
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keithvaluation.Property'),
        ),
    ]
