# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-26 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0008_auto_20171126_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
