# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0009_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lease_rate',
            field=models.IntegerField(blank=True, help_text=b'Lease price in dollars', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_rate_unit',
            field=models.CharField(blank=True, choices=[(b'month', b'month'), (b'year', b'year')], help_text=b'Is the least rate monthly or yearly?', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='keithvaluation.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True, help_text=b'When the property will be available for lease', null=True),
        ),
    ]
