# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0012_experttestimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='entry_points',
            field=models.TextField(blank=True, help_text=b'List of lat, long pairs (one per line) for entrypoint to the property', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='boundary_points',
            field=models.TextField(blank=True, help_text=b'List of lat, long pairs (one per line) tracing out the property', null=True),
        ),
    ]
