# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    Property = apps.get_model('keithvaluation', 'Property')
    for p in Property.objects.all():
        p.slug = slugify(p.property_name)
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0013_auto_20171129_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='invalid'),
            preserve_default=False,
        ),
        migrations.RunPython(set_slugs),
    ]
