# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0014_property_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
