# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'keithvaluation', '0017_auto_20181224_0358'), (b'keithvaluation', '0018_property_zoning'), (b'keithvaluation', '0019_property_city'), (b'keithvaluation', '0020_property_address')]

    dependencies = [
        ('keithvaluation', '0016_businesslisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['county', 'property_name', 'available_date'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='building_sqft',
            field=models.IntegerField(blank=True, help_text=b'Total square footage of all buildings on the property', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.IntegerField(blank=True, help_text=b'Sale price if for sale', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='available_for_lease',
            field=models.BooleanField(default=False, help_text=b'A property we are willing to lease (not hunting leases)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available_to_hunt',
            field=models.BooleanField(default=False, help_text=b'Is it hunting land that we lease out?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='boundary_points',
            field=models.TextField(blank=True, help_text=b'List of lat, long pairs (one per line, comma between lat and long) tracing out the property.  Multiple rings can be specified with a blank line between them', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, help_text=b'Zoning district/code of the property', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
