# Generated by Django 4.1.3 on 2022-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keithvaluation', '0017_auto_20181224_0358_squashed_0020_property_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondemnationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('property_type', models.CharField(max_length=256)),
                ('attorney', models.CharField(max_length=128)),
                ('appraiser', models.CharField(max_length=128)),
                ('condemnor_offer', models.PositiveIntegerField()),
                ('appraisers_estimate', models.PositiveIntegerField()),
                ('settlement', models.PositiveIntegerField()),
                ('is_jury_trial', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JudicialHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=128)),
                ('expert_witness', models.CharField(max_length=128)),
                ('jurisdiction', models.CharField(max_length=256)),
                ('appraiser_testimony', models.CharField(max_length=512)),
                ('agreed', models.BooleanField(default=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='ExpertTestimony',
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bvresearch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='economictrend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='available_date',
            field=models.DateField(blank=True, help_text='When the property will be available for lease', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='A longer description of the property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entry_points',
            field=models.TextField(blank=True, help_text='List of lat, long pairs (one per line) for entrypoint to the property', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_rate',
            field=models.IntegerField(blank=True, help_text='Lease price in dollars', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_rate_unit',
            field=models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], help_text='Is the least rate monthly or yearly?', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(help_text='A short name for the property', max_length=256),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('NC', 'NC')], max_length=256),
        ),
        migrations.AlterField(
            model_name='reresearch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reresearch',
            name='subtype',
            field=models.CharField(choices=[('Agricultural Properties', 'Agricultural Properties'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Damage Studies', 'Damage Studies'), ('Industrial', 'Industrial'), ('Land Development', 'Land Development'), ('Residential', 'Residential')], max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='headshots'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='order',
            field=models.PositiveIntegerField(help_text='Relative ordering of this staff member (lowest is higher up on the page)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
