#!/bin/bash

set -xe

sed \
  -e"s/<APP_HOSTNAME>/$APP_ENV_SITE_HOSTNAME/" \
  -e"s/<ADMIN_HOSTNAME>/$ADMIN_ENV_SITE_HOSTNAME/" \
  /tmp/site-template.conf > /etc/nginx/sites-enabled/keithvaluation.conf

mkdir -p /etc/nginx/ssl
echo -e "$ADMIN_SSL_CERT" > /etc/nginx/ssl/${ADMIN_ENV_SITE_HOSTNAME}.crt
echo -e "$ADMIN_SSL_KEY" > /etc/nginx/ssl/${ADMIN_ENV_SITE_HOSTNAME}.key

mkdir -p /logs/

if [[ -z $1 ]]
then
  exec /usr/sbin/nginx
else
  exec $@
fi
