---
- hosts: all
  become: true
  vars:
    project_name: kv
    code_dir: "/srv/keithvaluation"
  vars_files:
    - host_vars/{{inventory_hostname}}.yml
    - secrets/deploy_key.yml
  roles:
    - docker
    - keithvaluation
